config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/haddocking/prodigy:
      branch: setup
      repo: https://github.com/haddocking/prodigy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/haddocking/prodigy git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-brown-eel.sh
        container: qc.acc_stinky-plum-okapi
  QC.Doc:
    repos:
      github.com/haddocking/prodigy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-brown-ragdoll.sh
        container: qc.doc_leaky-pumpkin-cuttlefish
      github.com/haddocking/prodigy git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-cerulean-goose.sh
        container: qc.doc_stuffy-apricot-elephant
      github.com/haddocking/prodigy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-celadon-penguin.sh
        container: qc.doc_seedy-crimson-dachshund
  QC.Lic:
    repos:
      github.com/haddocking/prodigy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cornflower-dunker.sh
        container: qc.lic_pasty-plum-cichlid
  QC.Met:
    repos:
      github.com/haddocking/prodigy cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-russet-hummingbird.sh
        container: qc.met_pasty-rust-octopus
  QC.Sec:
    repos:
      github.com/haddocking/prodigy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-brown-camel.sh
        container: qc.sec_shabby-cinnamon-wolverine
  QC.Sty:
    repos:
      github.com/haddocking/prodigy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-tan-kangaroo.sh
        container: qc.sty_baggy-ivory-fish
      github.com/haddocking/prodigy jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-persimmon-donkey.sh
        container: qc.sty_gummy-cinnabar-mongrel
  QC.Ver:
    repos:
      github.com/haddocking/prodigy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-cyan-dogfish.sh
        container: qc.ver_lousy-fuchsia-ladybird
timeout: 5400
