config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/haddocking/prodigy:
      branch: main
      repo: https://github.com/haddocking/prodigy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/haddocking/prodigy git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-thistle-termite.sh
        container: qc.acc_skanky-carmine-chimpanzee
  QC.Doc:
    repos:
      github.com/haddocking/prodigy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-beige-devil.sh
        container: qc.doc_boozy-violet-cassowary
      github.com/haddocking/prodigy git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-salmon-budgerigar.sh
        container: qc.doc_paltry-viridian-bracke
      github.com/haddocking/prodigy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-olive-wombat.sh
        container: qc.doc_silly-cerise-rattlesnake
  QC.Lic:
    repos:
      github.com/haddocking/prodigy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-ivory-gecko.sh
        container: qc.lic_pokey-cyan-okapi
  QC.Sec:
    repos:
      github.com/haddocking/prodigy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-sepia-peccary.sh
        container: qc.sec_wheezy-carmine-hummingbird
  QC.Sty:
    repos:
      github.com/haddocking/prodigy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-magnolia-tamarin.sh
        container: qc.sty_trippy-lime-mayfly
      github.com/haddocking/prodigy jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-amaranth-spaniel.sh
        container: qc.sty_jumpy-cardinal-tarsier
  QC.Ver:
    repos:
      github.com/haddocking/prodigy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-emerald-capuchin.sh
        container: qc.ver_ugly-saffron-ragdoll
timeout: 5400
