config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/haddocking/prodigy:
      branch: main
      repo: https://github.com/haddocking/prodigy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/haddocking/prodigy git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-charcoal-oyster.sh
        container: qc.acc_whiny-tangerine-drever
  QC.Doc:
    repos:
      github.com/haddocking/prodigy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-purple-otter.sh
        container: qc.doc_gloppy-gamboge-kiwi
      github.com/haddocking/prodigy git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-fuchsia-sparrow.sh
        container: qc.doc_tasty-amaranth-flounder
      github.com/haddocking/prodigy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-charcoal-akbash.sh
        container: qc.doc_bluesy-taupe-guppy
  QC.Lic:
    repos:
      github.com/haddocking/prodigy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-magnolia-gorilla.sh
        container: qc.lic_woolly-ultramarine-sponge
  QC.Met:
    repos:
      github.com/haddocking/prodigy cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-seashell-setter.sh
        container: qc.met_droopy-ochre-weasel
  QC.Sec:
    repos:
      github.com/haddocking/prodigy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-brass-goose.sh
        container: qc.sec_woolly-rose-mole
  QC.Sty:
    repos:
      github.com/haddocking/prodigy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-zucchini-saola.sh
        container: qc.sty_fuzzy-zucchini-macaque
      github.com/haddocking/prodigy jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-persimmon-kakapo.sh
        container: qc.sty_crabby-coral-oyster
  QC.Ver:
    repos:
      github.com/haddocking/prodigy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-purple-starfish.sh
        container: qc.ver_shaggy-denim-akbash
timeout: 5400
