config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/haddocking/prodigy:
      branch: setup
      repo: https://github.com/haddocking/prodigy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/haddocking/prodigy git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-eggplant-crocodile.sh
        container: qc.acc_pokey-salmon-akbash
  QC.Doc:
    repos:
      github.com/haddocking/prodigy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-maroon-ostrich.sh
        container: qc.doc_ready-scarlet-chinook
      github.com/haddocking/prodigy git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-platinum-liger.sh
        container: qc.doc_wiggy-azure-fowl
      github.com/haddocking/prodigy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-bistre-llama.sh
        container: qc.doc_homely-chocolate-lemur
  QC.Lic:
    repos:
      github.com/haddocking/prodigy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-corn-lynx.sh
        container: qc.lic_surly-amaranth-ladybird
  QC.Met:
    repos:
      github.com/haddocking/prodigy cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-ivory-stingray.sh
        container: qc.met_skanky-yellow-sparrow
  QC.Sec:
    repos:
      github.com/haddocking/prodigy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-puce-wasp.sh
        container: qc.sec_queasy-russet-spitz
  QC.Sty:
    repos:
      github.com/haddocking/prodigy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-burgundy-havanese.sh
        container: qc.sty_squirrely-flax-lobster
      github.com/haddocking/prodigy jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-olive-spitz.sh
        container: qc.sty_skinny-periwinkle-dormouse
  QC.Ver:
    repos:
      github.com/haddocking/prodigy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-xanthic-heron.sh
        container: qc.ver_stuffy-mauve-worm
timeout: 5400
